### ISSUE TITLE
JSON option

### ISSUE THREAD

**Issue by bmish** [pmmmwh/staledeps#164]
The tool currently provides output in human-readable format.

To make this output easily consumable by other tools or useful for further data analysis, an option could be provided `-j` / `--json` to output a result like:

```json
[
  { "name": "eslint", "lastPublish": "2023-01-13T00:17:03+00:00" }
]
```

We would want to use an absolute date time format like [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) instead of a relative date of course.

If necessary at some point, there could also be a Node API for this kind of output, although a CLI json output may be sufficient at first.

**Comment by pmmmwh** [comment]
Let's say if we were to add JSON output - what would the expected behaviour for other logging (such as "processing" messages)?
